version: "3.7"

services:
    app:
        container_name: react-tracker-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

    server:
        container_name: react-tracker-server
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "8000:8000"

networks:
    app-network:
        driver: bridge
